class Country {
  final String name;
  final String code;
  final String dialCode;
  final int minLength;
  final int maxLength;

  const Country({
    required this.name,
    required this.code,
    required this.dialCode,
    required this.minLength,
    required this.maxLength,
  });
}

class CountryUtils {
  static const List<Country> countries = [
    Country(name: "Afghanistan", code: "AF", dialCode: "+93", minLength: 9, maxLength: 9),
    Country(name: "Albania", code: "AL", dialCode: "+355", minLength: 9, maxLength: 9),
    Country(name: "Algeria", code: "DZ", dialCode: "+213", minLength: 9, maxLength: 9),
    Country(name: "Andorra", code: "AD", dialCode: "+376", minLength: 6, maxLength: 6),
    Country(name: "Angola", code: "AO", dialCode: "+244", minLength: 9, maxLength: 9),
    Country(name: "Argentina", code: "AR", dialCode: "+54", minLength: 10, maxLength: 11),
    Country(name: "Armenia", code: "AM", dialCode: "+374", minLength: 8, maxLength: 8),
    Country(name: "Australia", code: "AU", dialCode: "+61", minLength: 9, maxLength: 9),
    Country(name: "Austria", code: "AT", dialCode: "+43", minLength: 10, maxLength: 13),
    Country(name: "Azerbaijan", code: "AZ", dialCode: "+994", minLength: 9, maxLength: 9),
    Country(name: "Bahrain", code: "BH", dialCode: "+973", minLength: 8, maxLength: 8),
    Country(name: "Bangladesh", code: "BD", dialCode: "+880", minLength: 10, maxLength: 10),
    Country(name: "Belarus", code: "BY", dialCode: "+375", minLength: 9, maxLength: 9),
    Country(name: "Belgium", code: "BE", dialCode: "+32", minLength: 9, maxLength: 9),
    Country(name: "Belize", code: "BZ", dialCode: "+501", minLength: 7, maxLength: 7),
    Country(name: "Benin", code: "BJ", dialCode: "+229", minLength: 8, maxLength: 8),
    Country(name: "Bhutan", code: "BT", dialCode: "+975", minLength: 8, maxLength: 8),
    Country(name: "Bolivia", code: "BO", dialCode: "+591", minLength: 8, maxLength: 8),
    Country(name: "Bosnia and Herzegovina", code: "BA", dialCode: "+387", minLength: 8, maxLength: 9),
    Country(name: "Botswana", code: "BW", dialCode: "+267", minLength: 8, maxLength: 8),
    Country(name: "Brazil", code: "BR", dialCode: "+55", minLength: 10, maxLength: 11),
    Country(name: "Brunei", code: "BN", dialCode: "+673", minLength: 7, maxLength: 7),
    Country(name: "Bulgaria", code: "BG", dialCode: "+359", minLength: 8, maxLength: 9),
    Country(name: "Burkina Faso", code: "BF", dialCode: "+226", minLength: 8, maxLength: 8),
    Country(name: "Burundi", code: "BI", dialCode: "+257", minLength: 8, maxLength: 8),
    Country(name: "Cambodia", code: "KH", dialCode: "+855", minLength: 8, maxLength: 9),
    Country(name: "Cameroon", code: "CM", dialCode: "+237", minLength: 8, maxLength: 9),
    Country(name: "Canada", code: "CA", dialCode: "+1", minLength: 10, maxLength: 10),
    Country(name: "Chad", code: "TD", dialCode: "+235", minLength: 8, maxLength: 8),
    Country(name: "Chile", code: "CL", dialCode: "+56", minLength: 9, maxLength: 9),
    Country(name: "China", code: "CN", dialCode: "+86", minLength: 11, maxLength: 11),
    Country(name: "Colombia", code: "CO", dialCode: "+57", minLength: 10, maxLength: 10),
    Country(name: "Costa Rica", code: "CR", dialCode: "+506", minLength: 8, maxLength: 8),
    Country(name: "Croatia", code: "HR", dialCode: "+385", minLength: 8, maxLength: 9),
    Country(name: "Cuba", code: "CU", dialCode: "+53", minLength: 8, maxLength: 8),
    Country(name: "Cyprus", code: "CY", dialCode: "+357", minLength: 8, maxLength: 8),
    Country(name: "Czech Republic", code: "CZ", dialCode: "+420", minLength: 9, maxLength: 9),
    Country(name: "Denmark", code: "DK", dialCode: "+45", minLength: 8, maxLength: 8),
    Country(name: "Dominican Republic", code: "DO", dialCode: "+1", minLength: 10, maxLength: 10),
    Country(name: "Ecuador", code: "EC", dialCode: "+593", minLength: 9, maxLength: 9),
    Country(name: "Egypt", code: "EG", dialCode: "+20", minLength: 10, maxLength: 10),
    Country(name: "El Salvador", code: "SV", dialCode: "+503", minLength: 8, maxLength: 8),
    Country(name: "Estonia", code: "EE", dialCode: "+372", minLength: 7, maxLength: 8),
    Country(name: "Ethiopia", code: "ET", dialCode: "+251", minLength: 9, maxLength: 9),
    Country(name: "Finland", code: "FI", dialCode: "+358", minLength: 9, maxLength: 10),
    Country(name: "France", code: "FR", dialCode: "+33", minLength: 9, maxLength: 9),
    Country(name: "Georgia", code: "GE", dialCode: "+995", minLength: 9, maxLength: 9),
    Country(name: "Germany", code: "DE", dialCode: "+49", minLength: 10, maxLength: 11),
    Country(name: "Ghana", code: "GH", dialCode: "+233", minLength: 9, maxLength: 9),
    Country(name: "Greece", code: "GR", dialCode: "+30", minLength: 10, maxLength: 10),
    Country(name: "Guatemala", code: "GT", dialCode: "+502", minLength: 8, maxLength: 8),
    Country(name: "Haiti", code: "HT", dialCode: "+509", minLength: 8, maxLength: 8),
    Country(name: "Honduras", code: "HN", dialCode: "+504", minLength: 8, maxLength: 8),
    Country(name: "Hungary", code: "HU", dialCode: "+36", minLength: 9, maxLength: 9),
    Country(name: "Iceland", code: "IS", dialCode: "+354", minLength: 7, maxLength: 7),
    Country(name: "India", code: "IN", dialCode: "+91", minLength: 10, maxLength: 10),
    Country(name: "Indonesia", code: "ID", dialCode: "+62", minLength: 9, maxLength: 12),
    Country(name: "Iran", code: "IR", dialCode: "+98", minLength: 10, maxLength: 10),
    Country(name: "Iraq", code: "IQ", dialCode: "+964", minLength: 10, maxLength: 10),
    Country(name: "Ireland", code: "IE", dialCode: "+353", minLength: 9, maxLength: 9),
    Country(name: "Israel", code: "IL", dialCode: "+972", minLength: 9, maxLength: 9),
    Country(name: "Italy", code: "IT", dialCode: "+39", minLength: 9, maxLength: 10),
    Country(name: "Jamaica", code: "JM", dialCode: "+1", minLength: 10, maxLength: 10),
    Country(name: "Japan", code: "JP", dialCode: "+81", minLength: 10, maxLength: 11),
    Country(name: "Jordan", code: "JO", dialCode: "+962", minLength: 9, maxLength: 9),
    Country(name: "Kazakhstan", code: "KZ", dialCode: "+7", minLength: 10, maxLength: 10),
    Country(name: "Kenya", code: "KE", dialCode: "+254", minLength: 9, maxLength: 9),
    Country(name: "Kuwait", code: "KW", dialCode: "+965", minLength: 8, maxLength: 8),
    Country(name: "Kyrgyzstan", code: "KG", dialCode: "+996", minLength: 9, maxLength: 9),
    Country(name: "Laos", code: "LA", dialCode: "+856", minLength: 9, maxLength: 10),
    Country(name: "Latvia", code: "LV", dialCode: "+371", minLength: 8, maxLength: 8),
    Country(name: "Lebanon", code: "LB", dialCode: "+961", minLength: 8, maxLength: 8),
    Country(name: "Libya", code: "LY", dialCode: "+218", minLength: 9, maxLength: 9),
    Country(name: "Lithuania", code: "LT", dialCode: "+370", minLength: 8, maxLength: 8),
    Country(name: "Luxembourg", code: "LU", dialCode: "+352", minLength: 9, maxLength: 9),
    Country(name: "Madagascar", code: "MG", dialCode: "+261", minLength: 9, maxLength: 9),
    Country(name: "Malaysia", code: "MY", dialCode: "+60", minLength: 9, maxLength: 10),
    Country(name: "Maldives", code: "MV", dialCode: "+960", minLength: 7, maxLength: 7),
    Country(name: "Mali", code: "ML", dialCode: "+223", minLength: 8, maxLength: 8),
    Country(name: "Malta", code: "MT", dialCode: "+356", minLength: 8, maxLength: 8),
    Country(name: "Mexico", code: "MX", dialCode: "+52", minLength: 10, maxLength: 10),
    Country(name: "Moldova", code: "MD", dialCode: "+373", minLength: 8, maxLength: 8),
    Country(name: "Mongolia", code: "MN", dialCode: "+976", minLength: 8, maxLength: 8),
    Country(name: "Morocco", code: "MA", dialCode: "+212", minLength: 9, maxLength: 9),
    Country(name: "Myanmar", code: "MM", dialCode: "+95", minLength: 7, maxLength: 10),
    Country(name: "Nepal", code: "NP", dialCode: "+977", minLength: 10, maxLength: 10),
    Country(name: "Netherlands", code: "NL", dialCode: "+31", minLength: 9, maxLength: 9),
    Country(name: "New Zealand", code: "NZ", dialCode: "+64", minLength: 8, maxLength: 10),
    Country(name: "Nigeria", code: "NG", dialCode: "+234", minLength: 10, maxLength: 11),
    Country(name: "North Korea", code: "KP", dialCode: "+850", minLength: 10, maxLength: 10),
    Country(name: "Norway", code: "NO", dialCode: "+47", minLength: 8, maxLength: 8),
    Country(name: "Oman", code: "OM", dialCode: "+968", minLength: 8, maxLength: 8),
    Country(name: "Pakistan", code: "PK", dialCode: "+92", minLength: 10, maxLength: 10),
    Country(name: "Panama", code: "PA", dialCode: "+507", minLength: 8, maxLength: 8),
    Country(name: "Paraguay", code: "PY", dialCode: "+595", minLength: 9, maxLength: 9),
    Country(name: "Peru", code: "PE", dialCode: "+51", minLength: 9, maxLength: 9),
    Country(name: "Philippines", code: "PH", dialCode: "+63", minLength: 10, maxLength: 10),
    Country(name: "Poland", code: "PL", dialCode: "+48", minLength: 9, maxLength: 9),
    Country(name: "Portugal", code: "PT", dialCode: "+351", minLength: 9, maxLength: 9),
    Country(name: "Qatar", code: "QA", dialCode: "+974", minLength: 8, maxLength: 8),
    Country(name: "Romania", code: "RO", dialCode: "+40", minLength: 9, maxLength: 9),
    Country(name: "Russia", code: "RU", dialCode: "+7", minLength: 10, maxLength: 10),
    Country(name: "Saudi Arabia", code: "SA", dialCode: "+966", minLength: 9, maxLength: 9),
    Country(name: "Singapore", code: "SG", dialCode: "+65", minLength: 8, maxLength: 8),
    Country(name: "South Africa", code: "ZA", dialCode: "+27", minLength: 9, maxLength: 9),
    Country(name: "South Korea", code: "KR", dialCode: "+82", minLength: 9, maxLength: 11),
    Country(name: "Spain", code: "ES", dialCode: "+34", minLength: 9, maxLength: 9),
    Country(name: "Sri Lanka", code: "LK", dialCode: "+94", minLength: 9, maxLength: 9),
    Country(name: "Sweden", code: "SE", dialCode: "+46", minLength: 9, maxLength: 10),
    Country(name: "Switzerland", code: "CH", dialCode: "+41", minLength: 9, maxLength: 9),
    Country(name: "Syria", code: "SY", dialCode: "+963", minLength: 9, maxLength: 9),
    Country(name: "Taiwan", code: "TW", dialCode: "+886", minLength: 9, maxLength: 9),
    Country(name: "Thailand", code: "TH", dialCode: "+66", minLength: 9, maxLength: 9),
    Country(name: "Turkey", code: "TR", dialCode: "+90", minLength: 10, maxLength: 10),
    Country(name: "Ukraine", code: "UA", dialCode: "+380", minLength: 9, maxLength: 9),
    Country(name: "United Arab Emirates", code: "AE", dialCode: "+971", minLength: 9, maxLength: 9),
    Country(name: "United Kingdom", code: "GB", dialCode: "+44", minLength: 10, maxLength: 10),
    Country(name: "United States", code: "US", dialCode: "+1", minLength: 10, maxLength: 10),
    Country(name: "Uruguay", code: "UY", dialCode: "+598", minLength: 8, maxLength: 9),
    Country(name: "Uzbekistan", code: "UZ", dialCode: "+998", minLength: 9, maxLength: 9),
    Country(name: "Venezuela", code: "VE", dialCode: "+58", minLength: 10, maxLength: 10),
    Country(name: "Vietnam", code: "VN", dialCode: "+84", minLength: 9, maxLength: 10),
    Country(name: "Yemen", code: "YE", dialCode: "+967", minLength: 9, maxLength: 9),
    Country(name: "Zambia", code: "ZM", dialCode: "+260", minLength: 9, maxLength: 9),
    Country(name: "Zimbabwe", code: "ZW", dialCode: "+263", minLength: 9, maxLength: 9),
  ];

  static Country? getCountryByCode(String code) {
    try {
      return countries.firstWhere(
            (c) => c.code.toUpperCase() == code.toUpperCase(),
      );
    } catch (e) {
      return null;
    }
  }
}
